name: Quality

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Create Conda environment
        uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39
        with:
          environment-file: environment.yml
          cache-environment: false

      - name: Run quality gate
        run: make quality
        shell: bash -el {0}
